server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:30336/data_service?useSSL=false&serverTimezone=UTC
#    url: jdbc:mysql://mysql:3306/data_service?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
    mapper-locations: classpath:mapper/*.xml
